// src/components/fragments/theme-toggle/theme-toggle.tsx
"use client";

import { ButtonIcon } from "@/components/ui/button-icon";
import { useTheme } from "next-themes";
import { BsMoonStars, BsSun } from "react-icons/bs";

// TODO: Animate icon theme change
// TODO: Link the navigation

export const ThemeToggle = () => {
  const { setTheme, resolvedTheme } = useTheme();

  const switchTheme: () => void = () => {
    switch (resolvedTheme) {
      case "light":
        setTheme("dark");
        break;
      case "dark":
        setTheme("light");
        break;
      default:
        setTheme("light");
        break;
    }
  };

  const toggleTheme = () => {
    if (!document.startViewTransition) switchTheme();

    document.startViewTransition(switchTheme);
  };

  return (
    <ButtonIcon
      onClick={toggleTheme}
      className="relative *:absolute *:top-1/2 *:transform *:-translate-y-1/2 *:transition-all *:duration-500 *:ease-out"
    >
      <BsMoonStars className="-rotate-180 scale-50 opacity-0 dark:rotate-0 dark:scale-100 dark:opacity-100" />
      <BsSun className="rotate-0 scale-100 opacity-100 dark:rotate-180 dark:scale-50 dark:opacity-0" />
    </ButtonIcon>
  );
};

// src/components/ThemeToggle.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import Icon from "@iconify/svelte";
	import ButtonIcon from "./ui/ButtonIcon.svelte";

  type ThemeMode = "dark" | "light";

  let isDark = $state(false);
  let isMounted = $state(false);

  const applyTheme = (mode: ThemeMode) => {
    document.documentElement.classList.toggle("dark", mode === "dark");
    localStorage.setItem("theme", mode);
    isDark = mode === "dark";
  };

  const resolveInitialTheme = (): ThemeMode => {
    const stored = localStorage.getItem("theme") as ThemeMode | null;
    if (stored === "dark" || stored === "light") return stored;

    return window.matchMedia("(prefers-color-scheme: dark)").matches
      ? "dark"
      : "light";
  };

  const toggleTheme = () => {
    if (!isMounted) return;
    const next = isDark ? "light" : "dark";
    applyTheme(next);
  };

  onMount(() => {
    isMounted = true;
    applyTheme(resolveInitialTheme());
  });
</script>

<ButtonIcon
  onclick={toggleTheme}
  class="relative *:absolute *:top-1/2 *:transform *:-translate-y-1/2 *:transition-all *:duration-500 *:ease-out"
>
	<Icon
		icon="lucide:moon"
		class="-rotate-180 scale-50 opacity-0 dark:rotate-0 dark:scale-100 dark:opacity-100"
	/>
	<Icon
		icon="lucide:sun"
		class="rotate-0 scale-100 opacity-100 dark:rotate-180 dark:scale-50 dark:opacity-0"
	/>
</ButtonIcon>
